import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_SMS_LOGIN_LOG;
    CREATE TABLE SYS_SMS_LOGIN_LOG(
        ID BIGINT NOT NULL,
        USER_ID BIGINT NOT NULL,
        USER_MOBILE_PHONE VARCHAR(20) NOT NULL,
        VERIFICATION_CODE VARCHAR(10) NOT NULL,
        SMS_PROVIDER_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        BOOL_SERVICE_STATE_ENUM SMALLINT NOT NULL DEFAULT  '2',
        MESSAGE_CONTENT VARCHAR(50) NOT NULL,
        BOOL_USE_ENUM SMALLINT NOT NULL DEFAULT  '2',
        IP_ADDRESS VARCHAR(50),
        USER_AGENT VARCHAR(500),
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_SMS_LOGIN_LOG IS '';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.ID IS '主键ID';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.USER_ID IS '用户ID:foreignKey';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.USER_MOBILE_PHONE IS '用户手机号:foreignKey';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.VERIFICATION_CODE IS '短信验证码';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.SMS_PROVIDER_TYPE_ENUM IS '服务商类型:[1=阿里云=ALIYUN,;2=腾讯云=TENCENT]max=2';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.BOOL_SERVICE_STATE_ENUM IS '服务商是否已验证:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.MESSAGE_CONTENT IS '短信完整内容';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.BOOL_USE_ENUM IS '是否已验证:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.IP_ADDRESS IS 'IP;地址';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.USER_AGENT IS '浏览器;UserAgent';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_SMS_LOGIN_LOG.CREATE_USER_ID IS '创建人';
    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_SMS_LOGIN_LOG
        `);
  }
}
