import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_FOLDER_INFO;
    CREATE TABLE SYS_FOLDER_INFO(
        ID BIGINT NOT NULL,
        PARENT_ID BIGINT NOT NULL,
        PARENT_IDS VARCHAR(250) NOT NULL,
        FOLDER_NAME VARCHAR(50) NOT NULL,
        RANKING SMALLINT NOT NULL DEFAULT  '100',
        DESCRIPTION VARCHAR(500),
        BOOL_TOP_ENUM SMALLINT NOT NULL DEFAULT  '2',
        STATE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        DELETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        UPDATE_DATE BIGINT NOT NULL,
        UPDATE_USER_ID BIGINT NOT NULL,
        DELETE_DATE BIGINT,
        DELETE_USER_ID BIGINT,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_FOLDER_INFO IS '';
    COMMENT ON COLUMN SYS_FOLDER_INFO.ID IS '主键ID';
    COMMENT ON COLUMN SYS_FOLDER_INFO.PARENT_ID IS '父ID';
    COMMENT ON COLUMN SYS_FOLDER_INFO.PARENT_IDS IS '父ID集:多个层级用英文逗号隔开';
    COMMENT ON COLUMN SYS_FOLDER_INFO.FOLDER_NAME IS '文件夹名称:treeName:oneParam;listParam';
    COMMENT ON COLUMN SYS_FOLDER_INFO.RANKING IS '排序:排序值越小越排前;max=100';
    COMMENT ON COLUMN SYS_FOLDER_INFO.DESCRIPTION IS '备注';
    COMMENT ON COLUMN SYS_FOLDER_INFO.BOOL_TOP_ENUM IS '是否置顶:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_FOLDER_INFO.STATE_ENUM IS '启用状态:[1=启用=ENABLE,;2=禁用=DISABLE]max=2';
    COMMENT ON COLUMN SYS_FOLDER_INFO.DELETE_ENUM IS '删除状态:[1=未删除=NOT_DELETED,;2=已删除=DELETED]max=2';
    COMMENT ON COLUMN SYS_FOLDER_INFO.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_FOLDER_INFO.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_FOLDER_INFO.CREATE_USER_ID IS '创建人';
    COMMENT ON COLUMN SYS_FOLDER_INFO.UPDATE_DATE IS '更新时间';
    COMMENT ON COLUMN SYS_FOLDER_INFO.UPDATE_USER_ID IS '更新人';
    COMMENT ON COLUMN SYS_FOLDER_INFO.DELETE_DATE IS '删除时间';
    COMMENT ON COLUMN SYS_FOLDER_INFO.DELETE_USER_ID IS '删除人';
    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_FOLDER_INFO
        `);
  }
}
