import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_MESSAGE_TEMPLATE;
    CREATE TABLE SYS_MESSAGE_TEMPLATE(
        ID BIGINT NOT NULL,
        DICT_ITEM_ID BIGINT NOT NULL,
        TEMPLATE_NAME VARCHAR(250) NOT NULL,
        TEMPLATE_CODE VARCHAR(250) NOT NULL,
        TEMPLATE_CONTENT VARCHAR NOT NULL,
        RANKING SMALLINT NOT NULL DEFAULT  '100',
        DESCRIPTION VARCHAR(500),
        STATE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        DELETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        UPDATE_DATE BIGINT NOT NULL,
        UPDATE_USER_ID BIGINT NOT NULL,
        DELETE_DATE BIGINT,
        DELETE_USER_ID BIGINT,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_MESSAGE_TEMPLATE IS '';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.ID IS '主键ID';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.DICT_ITEM_ID IS '模板类型字典ID';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.TEMPLATE_NAME IS '模板名称';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.TEMPLATE_CODE IS '模板编码:oneParam;listParam';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.TEMPLATE_CONTENT IS '模板内容';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.RANKING IS '排序:排序值越小越排前;max=100';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.DESCRIPTION IS '备注';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.STATE_ENUM IS '启用状态:[1=启用=ENABLE,;2=禁用=DISABLE]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.DELETE_ENUM IS '删除状态:[1=未删除=NOT_DELETED,;2=已删除=DELETED]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.CREATE_USER_ID IS '创建人';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.UPDATE_DATE IS '更新时间';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.UPDATE_USER_ID IS '更新人';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.DELETE_DATE IS '删除时间';
    COMMENT ON COLUMN SYS_MESSAGE_TEMPLATE.DELETE_USER_ID IS '删除人';
    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_MESSAGE_TEMPLATE
        `);
  }
}
