import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_USER;
    CREATE TABLE SYS_USER(
        ID BIGINT NOT NULL,
        USERNAME VARCHAR(50) NOT NULL,
        NICKNAME VARCHAR(100),
        REAL_NAME VARCHAR(50),
        USER_PASSWORD VARCHAR(50) NOT NULL,
        PASSWORD_SALT VARCHAR(10) NOT NULL,
        USER_EMAIL VARCHAR(50),
        TELEPHONE VARCHAR(20),
        MOBILE_PHONE VARCHAR(20),
        AVATAR_URL VARCHAR(500),
        GENDER_ENUM SMALLINT NOT NULL DEFAULT  '1',
        USER_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        REGISTER_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        REGISTER_ORIGIN_ENUM SMALLINT NOT NULL DEFAULT  '1',
        STATE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        DELETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        UPDATE_DATE BIGINT NOT NULL,
        UPDATE_USER_ID BIGINT NOT NULL,
        DELETE_DATE BIGINT,
        DELETE_USER_ID BIGINT,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_USER IS '';
    COMMENT ON COLUMN SYS_USER.ID IS '主键ID';
    COMMENT ON COLUMN SYS_USER.USERNAME IS '用户账号:oneParam';
    COMMENT ON COLUMN SYS_USER.NICKNAME IS '昵称:oneParam';
    COMMENT ON COLUMN SYS_USER.REAL_NAME IS '真实姓名:likeParam';
    COMMENT ON COLUMN SYS_USER.USER_PASSWORD IS '登录密码';
    COMMENT ON COLUMN SYS_USER.PASSWORD_SALT IS '密码盐:放于密码后面';
    COMMENT ON COLUMN SYS_USER.USER_EMAIL IS '邮箱地址:oneParam';
    COMMENT ON COLUMN SYS_USER.TELEPHONE IS '固话';
    COMMENT ON COLUMN SYS_USER.MOBILE_PHONE IS '手机号:oneParam';
    COMMENT ON COLUMN SYS_USER.AVATAR_URL IS '头像';
    COMMENT ON COLUMN SYS_USER.GENDER_ENUM IS '性别:[1=保密=PRIVACY,;2=男性=MALE, 3=女性=FEMALE]max=3';
    COMMENT ON COLUMN SYS_USER.USER_TYPE_ENUM IS '用户类型:[1=普通用户=USER,;2=后台管理员=ADMIN, 3=租户主账号=TENANT_ADMIN, 4=租户子账号=TENANT_SUB_ACCOUNT]max=4';
    COMMENT ON COLUMN SYS_USER.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_USER.REGISTER_TYPE_ENUM IS '注册方式:[1=系统预置=SYSTEM_INIT,;2=后台管理系统新增=MANAGEMENT_ADD, 3=主动注册=REGISTER, 4=被邀请注册=INVITE]max=4';
    COMMENT ON COLUMN SYS_USER.REGISTER_ORIGIN_ENUM IS '注册来源:[1=WEB方式=WEB,;2=安卓APP=ANDROID, 3=苹果APP=IOS, 4=H5=H5, 5=微信小程序=WEIXIN_MINI_PROGRAM, 6=微信公众号=WEIXIN_OFFICIAL_ACCOUNT]max=6';
    COMMENT ON COLUMN SYS_USER.STATE_ENUM IS '启用状态:[1=启用=ENABLE,;2=禁用=DISABLE]max=2';
    COMMENT ON COLUMN SYS_USER.DELETE_ENUM IS '删除状态:[1=未删除=NOT_DELETED,;2=已删除=DELETED]max=2';
    COMMENT ON COLUMN SYS_USER.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_USER.CREATE_USER_ID IS '创建人';
    COMMENT ON COLUMN SYS_USER.UPDATE_DATE IS '更新时间';
    COMMENT ON COLUMN SYS_USER.UPDATE_USER_ID IS '更新人';
    COMMENT ON COLUMN SYS_USER.DELETE_DATE IS '删除时间';
    COMMENT ON COLUMN SYS_USER.DELETE_USER_ID IS '删除人';    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table sys_user
        `);
  }
}
