import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_MESSAGE_LOG;
    CREATE TABLE SYS_MESSAGE_LOG(
        ID BIGINT NOT NULL,
        RECEIVE_USER_ID BIGINT NOT NULL,
        SEND_USER_ID BIGINT NOT NULL,
        DICT_ITEM_ID BIGINT NOT NULL,
        TEMPLATE_ID BIGINT NOT NULL,
        MESSAGE_TITLE VARCHAR(250) NOT NULL,
        MESSAGE_CONTENT VARCHAR NOT NULL,
        BOOL_SEND_SUCCESS_ENUM SMALLINT NOT NULL DEFAULT  '1',
        BOOL_RECEIVE_SUCCESS_ENUM SMALLINT NOT NULL DEFAULT  '1',
        BOOL_JOB_SEND_ENUM SMALLINT NOT NULL DEFAULT  '1',
        JOB_SEND_DATE BIGINT,
        STATE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        DELETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        UPDATE_DATE BIGINT NOT NULL,
        UPDATE_USER_ID BIGINT NOT NULL,
        DELETE_DATE BIGINT,
        DELETE_USER_ID BIGINT,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_MESSAGE_LOG IS '';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.ID IS '主键ID';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.RECEIVE_USER_ID IS '接收者ID:foreignKey';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.SEND_USER_ID IS '发送者ID:foreignKey';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.DICT_ITEM_ID IS '模板类型字典ID:foreignKey';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.TEMPLATE_ID IS '模板ID:foreignKey';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.MESSAGE_TITLE IS '消息名称';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.MESSAGE_CONTENT IS '消息内容';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.BOOL_SEND_SUCCESS_ENUM IS '是否发送成功:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.BOOL_RECEIVE_SUCCESS_ENUM IS '是否接收成功:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.BOOL_JOB_SEND_ENUM IS '是否定时发送:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.JOB_SEND_DATE IS '定时发送时间';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.STATE_ENUM IS '启用状态:[1=启用=ENABLE,;2=禁用=DISABLE]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.DELETE_ENUM IS '删除状态:[1=未删除=NOT_DELETED,;2=已删除=DELETED]max=2';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.CREATE_USER_ID IS '创建人';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.UPDATE_DATE IS '更新时间';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.UPDATE_USER_ID IS '更新人';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.DELETE_DATE IS '删除时间';
    COMMENT ON COLUMN SYS_MESSAGE_LOG.DELETE_USER_ID IS '删除人';
    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_MESSAGE_LOG
        `);
  }
}
