import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_EVENT_LOG;
    CREATE TABLE SYS_EVENT_LOG(
        ID BIGINT NOT NULL,
        USER_ID BIGINT,
        USERNAME VARCHAR(50),
        MESSAGE VARCHAR(250),
        EXECUTE_TIME BIGINT,
        REQUEST_DATE BIGINT,
        REQUEST_URL VARCHAR(500),
        REQUEST_METHOD VARCHAR(50),
        REQUEST_PARAM VARCHAR(500),
        BOOL_EXECUTE_SUCCESS_ENUM SMALLINT NOT NULL DEFAULT  '1',
        OPERATE_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        EXCEPTION_MSG VARCHAR(250),
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        IP_ADDRESS VARCHAR(50),
        IP_REGION VARCHAR(100),
        IP_REGION_COUNTRY VARCHAR(50),
        IP_REGION_PROVINCE VARCHAR(50),
        IP_REGION_CITY VARCHAR(50),
        IP_REGION_ISP VARCHAR(50),
        USER_AGENT VARCHAR(500),
        DEVICE_NAME VARCHAR(50),
        OS_NAME VARCHAR(50),
        BROWSER_NAME VARCHAR(50),
        BROWSER_LOCALE VARCHAR(50),
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_EVENT_LOG IS '';
    COMMENT ON COLUMN SYS_EVENT_LOG.ID IS '主键ID';
    COMMENT ON COLUMN SYS_EVENT_LOG.USER_ID IS '用户ID:foreignKey';
    COMMENT ON COLUMN SYS_EVENT_LOG.USERNAME IS '用户账号:oneParam;listParam';
    COMMENT ON COLUMN SYS_EVENT_LOG.MESSAGE IS '记录信息';
    COMMENT ON COLUMN SYS_EVENT_LOG.EXECUTE_TIME IS '执行时间:单位毫秒';
    COMMENT ON COLUMN SYS_EVENT_LOG.REQUEST_DATE IS '访问时间';
    COMMENT ON COLUMN SYS_EVENT_LOG.REQUEST_URL IS '请求;URL';
    COMMENT ON COLUMN SYS_EVENT_LOG.REQUEST_METHOD IS '请求方法名';
    COMMENT ON COLUMN SYS_EVENT_LOG.REQUEST_PARAM IS '请求参数';
    COMMENT ON COLUMN SYS_EVENT_LOG.BOOL_EXECUTE_SUCCESS_ENUM IS '是否执行成功:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_EVENT_LOG.OPERATE_TYPE_ENUM IS '事件类型:[1=查询=QUERY,;2=创建=CREATE, 3=修改对象=UPDATE_INFO,4=修改状态=UPDATE_STATE,5=删除=DELETE,6=导入=IMPORT,7=导出=EXPORT]max=7';
    COMMENT ON COLUMN SYS_EVENT_LOG.EXCEPTION_MSG IS '失败异常信息';
    COMMENT ON COLUMN SYS_EVENT_LOG.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_EVENT_LOG.IP_ADDRESS IS 'IP;地址';
    COMMENT ON COLUMN SYS_EVENT_LOG.IP_REGION IS 'IP;信息';
    COMMENT ON COLUMN SYS_EVENT_LOG.IP_REGION_COUNTRY IS 'IP;地址对应的国家';
    COMMENT ON COLUMN SYS_EVENT_LOG.IP_REGION_PROVINCE IS 'IP;地址对应的省';
    COMMENT ON COLUMN SYS_EVENT_LOG.IP_REGION_CITY IS 'IP;地址对应的市';
    COMMENT ON COLUMN SYS_EVENT_LOG.IP_REGION_ISP IS 'IP;地址对应的网络提供商';
    COMMENT ON COLUMN SYS_EVENT_LOG.USER_AGENT IS '浏览器;UserAgent';
    COMMENT ON COLUMN SYS_EVENT_LOG.DEVICE_NAME IS '设备名称';
    COMMENT ON COLUMN SYS_EVENT_LOG.OS_NAME IS '系统名称';
    COMMENT ON COLUMN SYS_EVENT_LOG.BROWSER_NAME IS '浏览器';
    COMMENT ON COLUMN SYS_EVENT_LOG.BROWSER_LOCALE IS '语言区域';
    COMMENT ON COLUMN SYS_EVENT_LOG.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_EVENT_LOG.CREATE_USER_ID IS '创建人';
    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_EVENT_LOG
        `);
  }
}
