import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_FILE_INFO;
    CREATE TABLE SYS_FILE_INFO(
        ID BIGINT NOT NULL,
        FOLDER_ID BIGINT NOT NULL,
        FILE_SHOW_NAME VARCHAR(200) NOT NULL,
        FILE_STORAGE_NAME VARCHAR(200) NOT NULL,
        FILE_SUFFIX VARCHAR(20),
        FILE_STORAGE_PATH VARCHAR(300) NOT NULL,
        FILE_FULL_URL VARCHAR(500),
        FILE_STORAGE_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        FILE_SIZE BIGINT NOT NULL,
        RANKING SMALLINT NOT NULL DEFAULT  '100',
        DESCRIPTION VARCHAR(500),
        BOOL_TOP_ENUM SMALLINT NOT NULL DEFAULT  '2',
        BOOL_OSS_COMPLETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        BOOL_OSS_DELETE_ENUM SMALLINT NOT NULL DEFAULT  '2',
        STATE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        DELETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
        TENANT_ID BIGINT NOT NULL DEFAULT  '1',
        CREATE_DATE BIGINT NOT NULL,
        CREATE_USER_ID BIGINT NOT NULL,
        UPDATE_DATE BIGINT NOT NULL,
        UPDATE_USER_ID BIGINT NOT NULL,
        DELETE_DATE BIGINT,
        DELETE_USER_ID BIGINT,
        PRIMARY KEY (ID)
    );
    
    COMMENT ON TABLE SYS_FILE_INFO IS '';
    COMMENT ON COLUMN SYS_FILE_INFO.ID IS '主键ID';
    COMMENT ON COLUMN SYS_FILE_INFO.FOLDER_ID IS '文件夹ID:foreignKey';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_SHOW_NAME IS '文件显示名称:oneParam;listParam';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_STORAGE_NAME IS '文件存储名称:oneParam;listParam';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_SUFFIX IS '文件后缀:oneParam;listParam';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_STORAGE_PATH IS '文件存储路径';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_FULL_URL IS '文件完整url路径';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_STORAGE_TYPE_ENUM IS '存储渠道:[1=阿里云=ALIYUN,;2=又拍云=UPYUN]max=2';
    COMMENT ON COLUMN SYS_FILE_INFO.FILE_SIZE IS '文件大小:单位字节byte';
    COMMENT ON COLUMN SYS_FILE_INFO.RANKING IS '排序:排序值越小越排前;max=100';
    COMMENT ON COLUMN SYS_FILE_INFO.DESCRIPTION IS '备注';
    COMMENT ON COLUMN SYS_FILE_INFO.BOOL_TOP_ENUM IS '是否置顶:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_FILE_INFO.BOOL_OSS_COMPLETE_ENUM IS '是否完成上传:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_FILE_INFO.BOOL_OSS_DELETE_ENUM IS 'OSS真实删除状态:[1=是=YES,;2=否=NO]max=2';
    COMMENT ON COLUMN SYS_FILE_INFO.STATE_ENUM IS '启用状态:[1=启用=ENABLE,;2=禁用=DISABLE]max=2';
    COMMENT ON COLUMN SYS_FILE_INFO.DELETE_ENUM IS '删除状态:[1=未删除=NOT_DELETED,;2=已删除=DELETED]max=2';
    COMMENT ON COLUMN SYS_FILE_INFO.TENANT_ID IS '所属租户';
    COMMENT ON COLUMN SYS_FILE_INFO.CREATE_DATE IS '创建时间';
    COMMENT ON COLUMN SYS_FILE_INFO.CREATE_USER_ID IS '创建人';
    COMMENT ON COLUMN SYS_FILE_INFO.UPDATE_DATE IS '更新时间';
    COMMENT ON COLUMN SYS_FILE_INFO.UPDATE_USER_ID IS '更新人';
    COMMENT ON COLUMN SYS_FILE_INFO.DELETE_DATE IS '删除时间';
    COMMENT ON COLUMN SYS_FILE_INFO.DELETE_USER_ID IS '删除人';
    
    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_FILE_INFO
        `);
  }
}
