import { AbstractMigration, ClientPostgreSQL } from "../../deps.ts";

export default class extends AbstractMigration<ClientPostgreSQL> {
  /** Runs on migrate */
  async up(): Promise<void> {
    await this.client.queryObject(`
    DROP TABLE IF EXISTS SYS_PERMISSION;
CREATE TABLE SYS_PERMISSION(
    ID BIGINT NOT NULL,
    PERMISSION_NAME VARCHAR(50) NOT NULL,
    PERMISSION_CODE VARCHAR(50) NOT NULL,
    PERMISSION_URL VARCHAR(500),
    BELONG_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
    PERMISSION_TYPE_ENUM SMALLINT NOT NULL DEFAULT  '1',
    PARENT_ID BIGINT NOT NULL,
    PARENT_IDS VARCHAR(250) NOT NULL,
    ICON_CLASS VARCHAR(250),
    VISIBLE_ENUM SMALLINT NOT NULL DEFAULT  '1',
    BOOL_EXT_LINK_ENUM SMALLINT NOT NULL DEFAULT  '2',
    BOOL_NEW_TAB_ENUM SMALLINT NOT NULL DEFAULT  '2',
    RANKING SMALLINT NOT NULL DEFAULT  '100',
    DESCRIPTION VARCHAR(500),
    STATE_ENUM SMALLINT NOT NULL DEFAULT  '1',
    DELETE_ENUM SMALLINT NOT NULL DEFAULT  '1',
    TENANT_ID BIGINT NOT NULL DEFAULT  '1',
    CREATE_DATE BIGINT NOT NULL,
    CREATE_USER_ID BIGINT NOT NULL,
    UPDATE_DATE BIGINT NOT NULL,
    UPDATE_USER_ID BIGINT NOT NULL,
    DELETE_DATE BIGINT,
    DELETE_USER_ID BIGINT,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_PERMISSION IS '';
COMMENT ON COLUMN SYS_PERMISSION.ID IS '主键ID';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_NAME IS '权限名称:treeName';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_CODE IS '权限标识码:oneParam;listParam';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_URL IS '路由地址:如果是外部链接则代表链接地址';
COMMENT ON COLUMN SYS_PERMISSION.BELONG_TYPE_ENUM IS '归属类型:[1=所以=ALL,;2=管理后台=ADMIN, 3=租户=TENANT]max=3';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_TYPE_ENUM IS '权限类型:[1=一级目录=TOP_DIRECTORY,;2=菜单=MENU, 3=按钮=BUTTON]max=3';
COMMENT ON COLUMN SYS_PERMISSION.PARENT_ID IS '父ID';
COMMENT ON COLUMN SYS_PERMISSION.PARENT_IDS IS '父ID集';
COMMENT ON COLUMN SYS_PERMISSION.ICON_CLASS IS '权限图标';
COMMENT ON COLUMN SYS_PERMISSION.VISIBLE_ENUM IS '显示状态:[1=显示=DISPLAY,;2=隐藏=HIDDEN]max=2';
COMMENT ON COLUMN SYS_PERMISSION.BOOL_EXT_LINK_ENUM IS '是否外链:[1=是=YES,;2=否=NO]max=2';
COMMENT ON COLUMN SYS_PERMISSION.BOOL_NEW_TAB_ENUM IS '是否新标签打开:[1=是=YES,;2=否=NO]max=2';
COMMENT ON COLUMN SYS_PERMISSION.RANKING IS '排序:排序值越小越排前;max=100';
COMMENT ON COLUMN SYS_PERMISSION.DESCRIPTION IS '备注';
COMMENT ON COLUMN SYS_PERMISSION.STATE_ENUM IS '启用状态:[1=启用=ENABLE,;2=禁用=DISABLE]max=2';
COMMENT ON COLUMN SYS_PERMISSION.DELETE_ENUM IS '删除状态:[1=未删除=NOT_DELETED,;2=已删除=DELETED]max=2';
COMMENT ON COLUMN SYS_PERMISSION.TENANT_ID IS '所属租户';
COMMENT ON COLUMN SYS_PERMISSION.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN SYS_PERMISSION.CREATE_USER_ID IS '创建人';
COMMENT ON COLUMN SYS_PERMISSION.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN SYS_PERMISSION.UPDATE_USER_ID IS '更新人';
COMMENT ON COLUMN SYS_PERMISSION.DELETE_DATE IS '删除时间';
COMMENT ON COLUMN SYS_PERMISSION.DELETE_USER_ID IS '删除人';

    `);
  }

  /** Runs on rollback */
  async down(): Promise<void> {
    await this.client.queryObject(`
            DROP table SYS_PERMISSION
        `);
  }
}
